---
title: "Grade analysis"
author: "Joséphine Laguardia"
format: html
---

```{r configuration}
#| message: false
here::i_am("r-101-grade-analysis-fork.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
```

# Question 1

```{r question 1}
#| message: false
grades <- vroom("grades.csv")
```

# Question 2

```{r}
knitr::kable(grades |> 
               summarise(min(Exam, na.rm = TRUE), 
                         max(Exam,na.rm = TRUE), 
                         median(Exam,na.rm = TRUE), 
                         mean(Exam,na.rm = TRUE)),
             col.names = c("Minimum grade", "Maximum grade", "Median grade", "Mean grade")
)
```

# Question 3

```{r}
miss_exam <- grades |> 
  count(is.na(Exam))
```
`r miss_exam[2,2]` students didn't take the final exam.

# Question 4

```{r}
ggplot(grades, aes(x=Exam)) +
  geom_bar(na.rm=TRUE)
```

# Question 5

```{r}
knitr::kable(grades |> 
  group_by(Group) |>
  summarise(n()),
  col.names = c("Group", "Number of students"))
```

# Question 6

```{r}
ggplot(grades, aes(x=Group))+
  geom_bar(na.rm=TRUE)
```

# Question 7
First representation:
```{r}
ggplot(grades, aes(x=Exam))+
  geom_bar(na.rm=TRUE)+
  facet_wrap(~Group)
```

Second representation:
```{r}
ggplot(grades, aes(x=Exam, fill=Group))+
  geom_bar(na.rm=TRUE)
```

# Question 8

```{r}
knitr::kable(grades |>
  group_by(Group) |>
  summarise(miss_exam_group= sum(is.na(Exam))),
  col.names= c("Group", "Number of students who missed the exam"))
```
# Question 9



